# Generated by Django 2.2 on 2021-12-06 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_w_templates_app', '0002_auto_20211206_0304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.CharField(max_length=255),
        ),
    ]
